build: Avoid unnecessary format() when building long options
When building a custom_target command line,

    '--opt=@0@'.format(x.full_path())

can be replaced with

    '--opt', x

which is simpler and avoids hiding the `x` dependency from Meson.  In some
cases we were declaring that dependency explicitly; stop doing so.

This should fix an occasional build error from build-aux/gen-resources.py
when glib is built as a parallel subproject:

    FileNotFoundError: [Errno 2] No such file or directory: '[...]/glib-2.80.0/gio/glib-compile-resources'

We can't just add glib_compile_resources to `depends` because `depends`
doesn't accept `external_program` arguments.