Visual Studio builds: use -utf-8 if available
This avoids the build from erroring out due to warning/error C4819 (Unicode
handling issue in the compiler), which is likely to occur on Chinese, Japanese
and Korean locales