meson.build: link with lintl if needed
Link with -lintl if needed to avoid the following build failure with
some toolchains (e.g. uclibc or musl):

/home/giuliobenetti/autobuild/run/instance-0/output-1/host/opt/ext-toolchain/bin/../lib/gcc/mips64el-buildroot-linux-uclibc/5.5.0/../../../../mips64el-buildroot-linux-uclibc/bin/ld: gdk-pixbuf/libgdk_pixbuf-2.0.so.0.4200.2.p/gdk-pixbuf-util.c.o: in function `_gdk_pixbuf_init_gettext':
gdk-pixbuf-util.c:(.text+0xbc0): undefined reference to `libintl_bindtextdomain'
/home/giuliobenetti/autobuild/run/instance-0/output-1/host/opt/ext-toolchain/bin/../lib/gcc/mips64el-buildroot-linux-uclibc/5.5.0/../../../../mips64el-buildroot-linux-uclibc/bin/ld: gdk-pixbuf-util.c:(.text+0xbc8): undefined reference to `libintl_bindtextdomain'

Fixes:
 - http://autobuild.buildroot.org/results/894359558100ea9637feba16deaf99923805d0f2

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>